# ============================================================
# Script 22: Time-dependent ROC analysis for LUAD MPCDS
#
# Purpose:
#   Evaluate prognostic discrimination of the fixed LUAD MPCDS
#   at 1, 3 and 5 years using IPCW time-dependent ROC analysis.
#
# Cohorts:
#   - TCGA-LUAD
#   - GSE68465
#   - GSE72094
#   - GSE31210
#   - GSE50081
#
# Important:
#   - Existing MPCDS scores are reused.
#   - The prognostic model is NOT refitted.
#   - Continuous MPCDS is used.
#   - No outcome-optimized cutoff is used.
#   - TCGA horizons remain 365/1095/1825 days to reproduce the
#     previously validated analysis exactly.
#   - GEO survival times generated by Script 21 are in months,
#     so GEO horizons are 12/36/60 months.
# ============================================================


# ------------------------------------------------------------
# 0. Shared project configuration
# ------------------------------------------------------------

source("03_scripts/00_project_config.R")


# ------------------------------------------------------------
# 1. Required package
# ------------------------------------------------------------

if (
  !requireNamespace(
    "timeROC",
    quietly = TRUE
  )
) {
  stop(
    "Package 'timeROC' is required. Install it with ",
    "install.packages('timeROC') and rerun Script 22."
  )
}


# ------------------------------------------------------------
# 2. Directories
# ------------------------------------------------------------

mpcds_dir <- file.path(
  results_dir,
  "mpcds"
)

external_validation_dir <- file.path(
  mpcds_dir,
  "external_validation"
)

roc_results_dir <- file.path(
  mpcds_dir,
  "time_dependent_ROC"
)

ensure_dir(
  roc_results_dir
)


# ------------------------------------------------------------
# 3. Cohort files
# ------------------------------------------------------------

tcga_file <- file.path(
  mpcds_dir,
  "TCGA_LUAD_MPCDS_patient_scores.csv"
)

geo_accessions <- c(
  "GSE68465",
  "GSE72094",
  "GSE31210",
  "GSE50081"
)

geo_files <- file.path(
  external_validation_dir,
  geo_accessions,
  paste0(
    geo_accessions,
    "_MPCDS_patient_scores.csv"
  )
)

check_files_exist(
  c(
    tcga_file,
    geo_files
  )
)


# ------------------------------------------------------------
# 4. Load and standardize TCGA input
# ------------------------------------------------------------

tcga <- read.csv(
  tcga_file,
  stringsAsFactors = FALSE,
  check.names = FALSE
)

required_tcga_columns <- c(
  "patient_id",
  "OS_time",
  "OS_status",
  "MPCDS"
)

stopifnot(
  all(
    required_tcga_columns %in%
      colnames(
        tcga
      )
  )
)

if (
  !"MPCDS_z" %in%
  colnames(
    tcga
  )
) {
  
  tcga$MPCDS_z <- as.numeric(
    scale(
      tcga$MPCDS
    )
  )
}

tcga_roc <- tcga[
  complete.cases(
    tcga[
      ,
      c(
        "OS_time",
        "OS_status",
        "MPCDS_z"
      )
    ]
  ) &
    tcga$OS_time >
    0 &
    tcga$OS_status %in%
    c(
      0,
      1
    ),
  ,
  drop = FALSE
]

stopifnot(
  nrow(
    tcga_roc
  ) == 504,
  sum(
    tcga_roc$OS_status
  ) == 182
)


# ------------------------------------------------------------
# 5. Load GEO MPCDS validation datasets from Script 21
# ------------------------------------------------------------

geo_data <- setNames(
  lapply(
    geo_files,
    function(
    file
    ) {
      
      dat <- read.csv(
        file,
        stringsAsFactors = FALSE,
        check.names = FALSE
      )
      
      required_columns <- c(
        "sample_id",
        "OS_time",
        "OS_status",
        "MPCDS",
        "MPCDS_z"
      )
      
      if (
        !all(
          required_columns %in%
          colnames(
            dat
          )
        )
      ) {
        stop(
          basename(
            file
          ),
          " is missing required Script 21 output columns."
        )
      }
      
      dat <- dat[
        complete.cases(
          dat[
            ,
            c(
              "OS_time",
              "OS_status",
              "MPCDS_z"
            )
          ]
        ) &
          dat$OS_time >
          0 &
          dat$OS_status %in%
          c(
            0,
            1
          ),
        ,
        drop = FALSE
      ]
      
      dat
    }
  ),
  geo_accessions
)

stopifnot(
  nrow(
    geo_data[["GSE68465"]]
  ) == 442,
  sum(
    geo_data[["GSE68465"]]$OS_status
  ) == 236,
  nrow(
    geo_data[["GSE72094"]]
  ) == 398,
  sum(
    geo_data[["GSE72094"]]$OS_status
  ) == 113,
  nrow(
    geo_data[["GSE31210"]]
  ) == 226,
  sum(
    geo_data[["GSE31210"]]$OS_status
  ) == 35,
  nrow(
    geo_data[["GSE50081"]]
  ) == 128,
  sum(
    geo_data[["GSE50081"]]$OS_status
  ) == 52
)


# ------------------------------------------------------------
# 6. ROC horizons
# ------------------------------------------------------------

roc_labels <- c(
  "1 year",
  "3 years",
  "5 years"
)

tcga_times <- c(
  365,
  1095,
  1825
)

geo_times <- c(
  12,
  36,
  60
)


# ------------------------------------------------------------
# 7. Follow-up support helper
# ------------------------------------------------------------

summarize_horizon_support <- function(
    time,
    status,
    horizons,
    labels,
    cohort,
    unit
) {
  
  out <- lapply(
    seq_along(
      horizons
    ),
    function(
    i
    ) {
      
      horizon <- horizons[
        i
      ]
      
      data.frame(
        cohort =
          cohort,
        timepoint =
          labels[
            i
          ],
        horizon =
          horizon,
        time_unit =
          unit,
        events_by_time =
          sum(
            status ==
              1 &
              time <=
              horizon
          ),
        known_survivors_beyond_time =
          sum(
            time >
              horizon
          ),
        censored_before_or_at_time =
          sum(
            status ==
              0 &
              time <=
              horizon
          ),
        total =
          length(
            time
          ),
        stringsAsFactors =
          FALSE
      )
    }
  )
  
  do.call(
    rbind,
    out
  )
}


# ------------------------------------------------------------
# 8. timeROC confidence-interval helper
# ------------------------------------------------------------

extract_auc_ci <- function(
    roc_object
) {
  
  ci_object <- stats::confint(
    roc_object,
    level = 0.95
  )
  
  ci <- ci_object$CI_AUC
  
  if (
    is.null(
      ci
    )
  ) {
    stop(
      "timeROC confidence intervals were not returned."
    )
  }
  
  ci <- as.matrix(
    ci
  )
  
  # timeROC 0.4.1 returns CI_AUC on a percentage scale.
  # This conditional conversion also remains safe if a future
  # version returns proportions directly.
  if (
    max(
      ci,
      na.rm = TRUE
    ) >
    1.5
  ) {
    ci <- ci /
      100
  }
  
  stopifnot(
    ncol(
      ci
    ) == 2,
    all(
      is.finite(
        ci
      )
    )
  )
  
  # Pointwise normal-approximation CIs from timeROC can extend
  # slightly below 0 or above 1, especially in smaller cohorts
  # or at late horizons. For reporting, truncate only the CI
  # limits to the admissible AUC range [0, 1]. The AUC estimate
  # itself is left unchanged.
  if (
    any(
      ci <
      0 |
      ci >
      1
    )
  ) {
    warning(
      "One or more timeROC CI limits extended outside [0,1]; ",
      "reporting limits were truncated to the admissible range."
    )
  }
  
  ci[
    ,
    1
  ] <- pmax(
    0,
    ci[
      ,
      1
    ]
  )
  
  ci[
    ,
    2
  ] <- pmin(
    1,
    ci[
      ,
      2
    ]
  )
  
  stopifnot(
    all(
      ci >=
        0 &
        ci <=
        1
    )
  )
  
  ci
}


# ------------------------------------------------------------
# 9. Generic time-dependent ROC function
# ------------------------------------------------------------

run_time_roc <- function(
    data,
    cohort,
    time_column,
    status_column,
    marker_column,
    horizons,
    labels,
    time_unit
) {
  
  time <- data[[time_column]]
  status <- data[[status_column]]
  marker <- data[[marker_column]]
  
  stopifnot(
    length(
      time
    ) ==
      length(
        status
      ),
    length(
      time
    ) ==
      length(
        marker
      ),
    all(
      status %in%
        c(
          0,
          1
        )
    ),
    all(
      is.finite(
        time
      )
    ),
    all(
      is.finite(
        marker
      )
    )
  )
  
  support <- summarize_horizon_support(
    time =
      time,
    status =
      status,
    horizons =
      horizons,
    labels =
      labels,
    cohort =
      cohort,
    unit =
      time_unit
  )
  
  roc <- timeROC::timeROC(
    T =
      time,
    delta =
      status,
    marker =
      marker,
    cause =
      1,
    weighting =
      "marginal",
    times =
      horizons,
    iid =
      TRUE
  )
  
  if (
    length(
      roc$AUC
    ) !=
    length(
      horizons
    )
  ) {
    stop(
      cohort,
      ": unexpected number of time-dependent AUC estimates."
    )
  }
  
  if (
    !all(
      is.finite(
        roc$AUC
      )
    )
  ) {
    stop(
      cohort,
      ": one or more time-dependent AUC estimates are non-finite."
    )
  }
  
  ci <- extract_auc_ci(
    roc
  )
  
  if (
    nrow(
      ci
    ) !=
    length(
      horizons
    )
  ) {
    stop(
      cohort,
      ": confidence-interval dimensions do not match horizons."
    )
  }
  
  summary <- data.frame(
    cohort =
      cohort,
    timepoint =
      labels,
    time_value =
      horizons,
    time_unit =
      time_unit,
    n =
      nrow(
        data
      ),
    events =
      sum(
        status ==
          1
      ),
    AUC =
      as.numeric(
        roc$AUC
      ),
    CI_lower =
      as.numeric(
        ci[
          ,
          1
        ]
      ),
    CI_upper =
      as.numeric(
        ci[
          ,
          2
        ]
      ),
    stringsAsFactors =
      FALSE
  )
  
  summary <- merge(
    summary,
    support,
    by =
      c(
        "cohort",
        "timepoint",
        "time_unit"
      ),
    all.x =
      TRUE,
    sort =
      FALSE
  )
  
  summary <- summary[
    match(
      labels,
      summary$timepoint
    ),
    ,
    drop = FALSE
  ]
  
  # Preserve the intended reporting order.
  rownames(
    summary
  ) <- NULL
  
  list(
    roc =
      roc,
    summary =
      summary,
    support =
      support
  )
}


# ------------------------------------------------------------
# 10. TCGA-LUAD time-dependent ROC
# ------------------------------------------------------------

cat(
  "\n============================================================\n",
  "TCGA-LUAD TIME-DEPENDENT ROC\n",
  "============================================================\n",
  sep = ""
)

tcga_result <- run_time_roc(
  data =
    tcga_roc,
  cohort =
    "TCGA-LUAD",
  time_column =
    "OS_time",
  status_column =
    "OS_status",
  marker_column =
    "MPCDS_z",
  horizons =
    tcga_times,
  labels =
    roc_labels,
  time_unit =
    "days"
)

print(
  tcga_result$summary,
  row.names = FALSE
)


# ------------------------------------------------------------
# 11. Regression check against previously validated TCGA AUCs
# ------------------------------------------------------------

expected_tcga_auc <- c(
  0.7054308,
  0.7091707,
  0.6493443
)

stopifnot(
  max(
    abs(
      tcga_result$summary$AUC -
        expected_tcga_auc
    )
  ) <
    1e-5
)


# ------------------------------------------------------------
# 12. External GEO time-dependent ROC
# ------------------------------------------------------------

geo_results <- vector(
  "list",
  length(
    geo_accessions
  )
)

names(
  geo_results
) <- geo_accessions

for (
  accession in geo_accessions
) {
  
  cat(
    "\n============================================================\n",
    accession,
    " TIME-DEPENDENT ROC\n",
    "============================================================\n",
    sep = ""
  )
  
  geo_results[[accession]] <- run_time_roc(
    data =
      geo_data[[accession]],
    cohort =
      accession,
    time_column =
      "OS_time",
    status_column =
      "OS_status",
    marker_column =
      "MPCDS_z",
    horizons =
      geo_times,
    labels =
      roc_labels,
    time_unit =
      "months"
  )
  
  print(
    geo_results[[accession]]$summary,
    row.names = FALSE
  )
  
  write.csv(
    geo_results[[accession]]$support,
    file.path(
      roc_results_dir,
      paste0(
        accession,
        "_time_dependent_ROC_horizon_support.csv"
      )
    ),
    row.names = FALSE
  )
}


# ------------------------------------------------------------
# 13. Regression check against established GSE68465 AUCs
# ------------------------------------------------------------

expected_gse68465_auc <- c(
  0.6453905,
  0.6374743,
  0.5856052
)

stopifnot(
  max(
    abs(
      geo_results[["GSE68465"]]$summary$AUC -
        expected_gse68465_auc
    )
  ) <
    1e-5
)


# ------------------------------------------------------------
# 14. Save TCGA horizon support
# ------------------------------------------------------------

write.csv(
  tcga_result$support,
  file.path(
    roc_results_dir,
    "TCGA_LUAD_time_dependent_ROC_horizon_support.csv"
  ),
  row.names = FALSE
)


# ------------------------------------------------------------
# 15. Combined AUC summary
# ------------------------------------------------------------

combined_summary <- do.call(
  rbind,
  c(
    list(
      tcga_result$summary
    ),
    lapply(
      geo_results,
      function(
    x
      ) {
        x$summary
      }
    )
  )
)

rownames(
  combined_summary
) <- NULL

# Use a stable cohort order.
cohort_order <- c(
  "TCGA-LUAD",
  geo_accessions
)

combined_summary$cohort <- factor(
  combined_summary$cohort,
  levels =
    cohort_order
)

combined_summary$timepoint <- factor(
  combined_summary$timepoint,
  levels =
    roc_labels
)

combined_summary <- combined_summary[
  order(
    combined_summary$cohort,
    combined_summary$timepoint
  ),
  ,
  drop = FALSE
]

combined_summary$cohort <- as.character(
  combined_summary$cohort
)

combined_summary$timepoint <- as.character(
  combined_summary$timepoint
)

rownames(
  combined_summary
) <- NULL

write.csv(
  combined_summary,
  file.path(
    roc_results_dir,
    "LUAD_MPCDS_time_dependent_ROC_all_cohorts.csv"
  ),
  row.names = FALSE
)


# ------------------------------------------------------------
# 16. External-only AUC summary
# ------------------------------------------------------------

external_summary <- combined_summary[
  combined_summary$cohort !=
    "TCGA-LUAD",
  ,
  drop = FALSE
]

write.csv(
  external_summary,
  file.path(
    roc_results_dir,
    "LUAD_MPCDS_external_GEO_time_dependent_ROC_summary.csv"
  ),
  row.names = FALSE
)


# ------------------------------------------------------------
# 17. Horizon-wise descriptive external summary
#
# This is descriptive only; it is NOT a meta-analysis.
# ------------------------------------------------------------

external_horizon_summary <- do.call(
  rbind,
  lapply(
    roc_labels,
    function(
    label
    ) {
      
      dat <- external_summary[
        external_summary$timepoint ==
          label,
        ,
        drop = FALSE
      ]
      
      data.frame(
        timepoint =
          label,
        n_external_cohorts =
          nrow(
            dat
          ),
        median_AUC =
          stats::median(
            dat$AUC
          ),
        min_AUC =
          min(
            dat$AUC
          ),
        max_AUC =
          max(
            dat$AUC
          ),
        cohorts_AUC_above_0_5 =
          sum(
            dat$AUC >
              0.5
          ),
        total_events_by_time =
          sum(
            dat$events_by_time
          ),
        total_known_survivors_beyond_time =
          sum(
            dat$known_survivors_beyond_time
          ),
        stringsAsFactors =
          FALSE
      )
    }
  )
)

write.csv(
  external_horizon_summary,
  file.path(
    roc_results_dir,
    "LUAD_MPCDS_external_GEO_time_dependent_ROC_horizon_summary.csv"
  ),
  row.names = FALSE
)


# ------------------------------------------------------------
# 18. Save R objects for later figure generation
# ------------------------------------------------------------

saveRDS(
  list(
    TCGA_LUAD =
      tcga_result$roc,
    GSE68465 =
      geo_results[["GSE68465"]]$roc,
    GSE72094 =
      geo_results[["GSE72094"]]$roc,
    GSE31210 =
      geo_results[["GSE31210"]]$roc,
    GSE50081 =
      geo_results[["GSE50081"]]$roc
  ),
  file.path(
    roc_results_dir,
    "LUAD_MPCDS_timeROC_objects.rds"
  )
)


# ------------------------------------------------------------
# 19. Final integrity checks
# ------------------------------------------------------------

stopifnot(
  nrow(
    combined_summary
  ) == 15,
  nrow(
    external_summary
  ) == 12,
  nrow(
    external_horizon_summary
  ) == 3,
  all(
    is.finite(
      combined_summary$AUC
    )
  ),
  all(
    combined_summary$AUC >=
      0 &
      combined_summary$AUC <=
      1
  ),
  all(
    combined_summary$CI_lower >=
      0 &
      combined_summary$CI_lower <=
      1
  ),
  all(
    combined_summary$CI_upper >=
      0 &
      combined_summary$CI_upper <=
      1
  )
)


# ------------------------------------------------------------
# 20. Completion summary
# ------------------------------------------------------------

cat(
  "\n============================================================\n",
  "SCRIPT 22 LUAD MPCDS TIME-DEPENDENT ROC SUMMARY\n",
  "============================================================\n",
  sep = ""
)

print(
  combined_summary[
    ,
    c(
      "cohort",
      "timepoint",
      "n",
      "events",
      "AUC",
      "CI_lower",
      "CI_upper",
      "events_by_time",
      "known_survivors_beyond_time",
      "censored_before_or_at_time"
    )
  ],
  row.names = FALSE
)

cat(
  "\nExternal GEO horizon summary:\n"
)

print(
  external_horizon_summary,
  row.names = FALSE
)

cat(
  "\nPreviously established regression checks:\n",
  "TCGA-LUAD 1/3/5-year AUCs reproduced: YES\n",
  "GSE68465 1/3/5-year AUCs reproduced: YES\n",
  "\nOutputs: ",
  roc_results_dir,
  "\n",
  sep = ""
)

cat(
  "============================================================\n",
  "\n========================================\n",
  "SCRIPT 22 COMPLETED SUCCESSFULLY\n",
  "========================================\n",
  sep = ""
)

# ============================================================
# End of script
# ============================================================